title: .butteredtoast
description: >
  Omar (.butteredtoast) | tjcsc | web writeups (the ones i understand)
url: https://karmaticow.github.io
baseurl: "/ctf"
markdown: kramdown
kramdown:
  input: GFM

author:
  name: ".butteredtoast (Omar)"
  email: ""

plugins:
  - jemoji
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

defaults:
  - scope:
      path: "write-ups"
    values:
      layout: "post"
exclude: ["sitemap.xml", "feed.xml", "LICENSE", "README.md"]
